package view;

import Business.BDonThanhToan;
import Business.BKhachHang;
import Business.BLoaiPhongHat;
import Business.BPhongHat;
import common.MyStrings;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.DonThanhToan;
import model.KhachHang;
import model.LoaiPhongHat;
import model.PhongHat;

/**
 *
 * @author thanhtri
 */
public class Dialog_SuaDonDatPhong extends javax.swing.JDialog {

    DefaultTableModel dfmPhong;
    Frame_NhanVien fNhanVien;
    DonThanhToan gDonDatPhong;

    public Dialog_SuaDonDatPhong(java.awt.Frame parent, boolean modal, DonThanhToan donDatPhong) {
        super(parent, modal);
        initComponents();
        fNhanVien = (Frame_NhanVien) parent;
        gDonDatPhong = donDatPhong;
        customInit();
    }

    void customInit() {
        tfMaPhong.setEditable(false);
        ((JTextField) tfNgay.getDateEditor()).setEditable(false);
        dfmPhong = (DefaultTableModel) tbPhong.getModel();
        tbPhong.setRowHeight(30);
        
        BLoaiPhongHat bLoaiPhongHat = new BLoaiPhongHat();
        ArrayList<LoaiPhongHat> arrLPH = null;
        BKhachHang bKhachHang = new BKhachHang();
        ArrayList<KhachHang> arrKH = null;

        try {
            arrKH = bKhachHang.layTatCaKhachHang();
        } catch (SQLException ex) {
            Logger.getLogger(Frame_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (int i = 0; i < arrKH.size(); i++) {
            Integer maKH = arrKH.get(i).getMaKH();
            cbbMaKH.addItem(maKH.toString());
        }
        
        BPhongHat bPhongHat = new BPhongHat();
        ArrayList<PhongHat> arrPH = null;

        try {
            arrPH = bPhongHat.layThongTinPhongHatTheoTinhTrang("Còn trống");
        } catch (SQLException ex) {
            Logger.getLogger(Dialog_SuaDonDatPhong.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (int i = 0; i < arrPH.size(); i++) {
            LoaiPhongHat lph = new LoaiPhongHat();
            try {
                lph = bLoaiPhongHat.layThongTinLoaiPhongHatTheoMa(arrPH.get(i).getMaLoaiPhong());
            } catch (SQLException ex) {
                Logger.getLogger(Dialog_SuaDonDatPhong.class.getName()).log(Level.SEVERE, null, ex);
            }
            dfmPhong.addRow(new Object[]{
                arrPH.get(i).getMaPhong(),
                lph.getSucChua(),
                lph.getGiaPhong()
            });
        }
        showData();
    }
    
    private void showData(){
        Integer maPhong = gDonDatPhong.getMaPhong();
        Integer maKH = gDonDatPhong.getMaKhachHang();
        String tgbd = gDonDatPhong.getThoiGianBatDau().toString();
        String ngayBD = tgbd.substring(0, 10);
        String gioBD = tgbd.substring(11, 16);
        
        tfMaPhong.setText(maPhong.toString());
        ((JTextField) tfNgay.getDateEditor()).setText(ngayBD);
        for(int i = 0; i < cbbMaKH.getItemCount(); i++){
            if(cbbMaKH.getItemAt(i).toString().equals(maKH.toString())){
                cbbMaKH.setSelectedIndex(i);
            }
        }
        for(int i = 0; i < cbbTuLuc.getItemCount(); i++){
            if(cbbTuLuc.getItemAt(i).toString().equals(gioBD)){
                cbbTuLuc.setSelectedIndex(i);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        spPhong = new javax.swing.JScrollPane();
        tbPhong = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfNgay = new com.toedter.calendar.JDateChooser();
        cbbTuLuc = new javax.swing.JComboBox<>();
        btnLuu = new javax.swing.JButton();
        cbbMaKH = new javax.swing.JComboBox<>();
        tfMaPhong = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(10, 125, 39));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 33)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ĐƠN ĐẶT PHÒNG");

        tbPhong.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tbPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phòng", "Sức chứa", "Đơn giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPhongMouseClicked(evt);
            }
        });
        spPhong.setViewportView(tbPhong);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mã khách hàng");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Từ lúc");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ngày");

        tfNgay.setDateFormatString("yyyy-MM-dd");
        tfNgay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cbbTuLuc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbbTuLuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00" }));

        btnLuu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(10, 125, 39));
        btnLuu.setText("LƯU");
        btnLuu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        cbbMaKH.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tfMaPhong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mã phòng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(tfNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbbTuLuc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbbMaKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(spPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addComponent(spPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbbTuLuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        BDonThanhToan bDonDatPhong = new BDonThanhToan();
        
        String date = ((JTextField)tfNgay.getDateEditor().getUiComponent()).getText();
        
        if (date.isEmpty()){
            JOptionPane.showMessageDialog(this, MyStrings.Please_Choose_Date);
            return;
        }
        
        int makh = Integer.parseInt(cbbMaKH.getSelectedItem().toString());
        int maphong = Integer.parseInt(tfMaPhong.getText());
        int giaphong = gDonDatPhong.getGiaPhong();
        String time = cbbTuLuc.getSelectedItem().toString();
        date = date + " " + time + ":00.0";
        
        LocalDateTime today = LocalDateTime.now();
        String sToday = DateTimeFormatter.ofPattern("yyyy-MM-dd hh:mm:ss.s", Locale.ENGLISH).format(today);

        if(date.compareTo(sToday) <= 0){
            JOptionPane.showMessageDialog(rootPane, MyStrings.Invalid_Start_Time);
            return;
        }
        
        boolean res = false;
        
        try {
            res = bDonDatPhong.capNhatDonDatPhong(gDonDatPhong.getMaDon(), makh, maphong, giaphong, date, "Chưa thanh toán");
        } catch (SQLException ex) {
            Logger.getLogger(Dialog_SuaDonDatPhong.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(res){
            this.fNhanVien.refreshPanelDonDatPhong();
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this,MyStrings.Edit_Failed);
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void tbPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPhongMouseClicked
        int r = tbPhong.getSelectedRow();
        if (r != -1){
            String maphong = dfmPhong.getValueAt(r, 0).toString();
            tfMaPhong.setText(maphong);
            int donGia = Integer.parseInt(dfmPhong.getValueAt(r, 2).toString());
            gDonDatPhong.setGiaPhong(donGia);
        }
    }//GEN-LAST:event_tbPhongMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JComboBox<String> cbbMaKH;
    private javax.swing.JComboBox<String> cbbTuLuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane spPhong;
    private javax.swing.JTable tbPhong;
    private javax.swing.JTextField tfMaPhong;
    private com.toedter.calendar.JDateChooser tfNgay;
    // End of variables declaration//GEN-END:variables
}
